name: myenv
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - expat=2.7.3=h9214b88_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.11.14=h981015d_0
  - setuptools=80.9.0=py311haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - accelerate==1.12.0
      - aiofiles==23.2.1
      - aistudio-sdk==0.3.8
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.11.0
      - bce-python-sdk==0.9.53
      - beautifulsoup4==4.14.2
      - brotli==1.2.0
      - certifi==2025.11.12
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - colorlog==6.10.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - distro==1.9.0
      - fastapi==0.122.0
      - ffmpy==1.0.0
      - filelock==3.20.0
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - future==1.0.0
      - gradio==4.44.1
      - gradio-client==1.3.0
      - groovy==0.1.2
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - imagesize==1.4.1
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - jiter==0.12.0
      - kiwisolver==1.4.9
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - modelscope==1.32.0
      - mpmath==1.3.0
      - networkx==3.6
      - numpy==2.3.5
      - openai==2.8.1
      - opencv-contrib-python==4.10.0.84
      - orjson==3.11.4
      - packaging==25.0
      - paddleocr==3.3.2
      - paddlex==3.3.10
      - pandas==2.3.3
      - pillow==10.4.0
      - prettytable==3.17.0
      - protobuf==6.33.1
      - psutil==7.1.3
      - py-cpuinfo==9.0.0
      - pyclipper==1.3.0.post6
      - pycryptodome==3.23.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pygments==2.19.2
      - pymupdf==1.26.6
      - pyparsing==3.2.5
      - pypdfium2==5.1.0
      - python-bidi==0.6.7
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.11.3
      - requests==2.32.5
      - rich==14.2.0
      - ruamel-yaml==0.18.16
      - ruamel-yaml-clib==0.2.15
      - ruff==0.14.6
      - safehttpx==0.1.7
      - safetensors==0.7.0
      - semantic-version==2.10.0
      - sentencepiece==0.2.1
      - shapely==2.1.2
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.8
      - starlette==0.50.0
      - sympy==1.14.0
      - tokenizers==0.22.1
      - tomlkit==0.12.0
      - torch==2.9.1
      - tqdm==4.67.1
      - transformers==4.57.3
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - ujson==5.11.0
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - wcwidth==0.2.14
      - websockets==12.0
prefix: D:\Downloads\anaconda\envs\myenv
